'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavbarHeader from '@/components/Navbar'
import Footer from '@/components/Footer'
import { QueryClient, QueryClientProvider } from 'react-query'
import NextTopLoader from 'nextjs-toploader'
import { Poppins } from 'next/font/google'
import { ToastContainer, toast } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { DataProvider } from '@/context/DataProjectContext'
const inter = Inter({ subsets: ['latin'] })
const client = new QueryClient()
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // You can adjust weights
})
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>

        <QueryClientProvider client={client}>
          <DataProvider>
            <NextTopLoader
              showSpinner={false}
              color="rgba(146, 222, 237, 1)"
              initialPosition={0.08}
              crawlSpeed={200}
              height={10}
              crawl={true}
              easing="ease"
              speed={200}
              shadow="0 0 0px hsl(229 100% 62%),0 0 0px hsl(229 100% 62%)"
              template='<div class="bar" role="bar"><div class="peg"></div></div><div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
              zIndex={1600}
              showAtBottom={false}
            />
            {/* <NavbarHeader/> */}

            <div
            //  className="p-4 md:p-8 lg:p-16"
             >
              {children}
            </div>




            <ToastContainer />
          </DataProvider>
        </QueryClientProvider>




      </body>
    </html>
  )
}
